version: 2.1

jobs:
  robonito-tests:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Trigger Robonito tests
          command: |
            # Add this value as a CircleCI project environment variable named ROBONITO_API_KEY: rb_cb1eac7376ff4c0c9b440cf30e004c67
            curl -sS -X POST "http://localhost:3000/app-server/integration/circleci/trigger/f27b610b-06fa-4685-8739-e197649c9e73" \
              -H "Content-Type: application/json" \
              -H "x-robonito-api-key: $ROBONITO_API_KEY" \
              -d '{
              "suiteId": "2099b2b6-f5a3-45f3-9070-f0acb6691f0c",
              "testCaseIds": ["9e167d0e-01c1-4727-80bc-1d9c833e7a71"],
              "circleciJobName": "$CIRCLE_JOB",
              "circleciBuildNumber": '$CIRCLE_BUILD_NUM'
            }'

workflows:
  robonito:
    jobs:
      - robonito-tests
